// flow-typed signature: 41c0653f0483b0b60377f17d8ec6263f
// flow-typed version: <<STUB>>/ajax-interceptor_v^1.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ajax-interceptor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ajax-interceptor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ajax-interceptor/index' {
  declare module.exports: $Exports<'ajax-interceptor'>;
}
declare module 'ajax-interceptor/index.js' {
  declare module.exports: $Exports<'ajax-interceptor'>;
}
