// flow-typed signature: 850603fed1a419651d653eec474c1692
// flow-typed version: <<STUB>>/barba.js_v^1.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'barba.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'barba.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'barba.js/dist/barba' {
  declare module.exports: any;
}

declare module 'barba.js/dist/barba.min' {
  declare module.exports: any;
}

declare module 'barba.js/karma.conf' {
  declare module.exports: any;
}

declare module 'barba.js/src/Cache/BaseCache' {
  declare module.exports: any;
}

declare module 'barba.js/src/Dispatcher/Dispatcher' {
  declare module.exports: any;
}

declare module 'barba.js/src/index' {
  declare module.exports: any;
}

declare module 'barba.js/src/Pjax/Dom' {
  declare module.exports: any;
}

declare module 'barba.js/src/Pjax/HistoryManager' {
  declare module.exports: any;
}

declare module 'barba.js/src/Pjax/Pjax' {
  declare module.exports: any;
}

declare module 'barba.js/src/Pjax/Prefetch' {
  declare module.exports: any;
}

declare module 'barba.js/src/Transition/BaseTransition' {
  declare module.exports: any;
}

declare module 'barba.js/src/Transition/HideShowTransition' {
  declare module.exports: any;
}

declare module 'barba.js/src/Utils/Utils' {
  declare module.exports: any;
}

declare module 'barba.js/src/View/BaseView' {
  declare module.exports: any;
}

declare module 'barba.js/tests/barba-test' {
  declare module.exports: any;
}

declare module 'barba.js/tests/cache-test' {
  declare module.exports: any;
}

declare module 'barba.js/tests/dispatcher-test' {
  declare module.exports: any;
}

declare module 'barba.js/tests/dom-test' {
  declare module.exports: any;
}

declare module 'barba.js/tests/e2e/test-1/index' {
  declare module.exports: any;
}

declare module 'barba.js/tests/e2e/test-1/test' {
  declare module.exports: any;
}

declare module 'barba.js/tests/history-test' {
  declare module.exports: any;
}

declare module 'barba.js/tests/index' {
  declare module.exports: any;
}

declare module 'barba.js/tests/pjax-test' {
  declare module.exports: any;
}

declare module 'barba.js/tests/utils-test' {
  declare module.exports: any;
}

declare module 'barba.js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'barba.js/dist/barba.js' {
  declare module.exports: $Exports<'barba.js/dist/barba'>;
}
declare module 'barba.js/dist/barba.min.js' {
  declare module.exports: $Exports<'barba.js/dist/barba.min'>;
}
declare module 'barba.js/karma.conf.js' {
  declare module.exports: $Exports<'barba.js/karma.conf'>;
}
declare module 'barba.js/src/Cache/BaseCache.js' {
  declare module.exports: $Exports<'barba.js/src/Cache/BaseCache'>;
}
declare module 'barba.js/src/Dispatcher/Dispatcher.js' {
  declare module.exports: $Exports<'barba.js/src/Dispatcher/Dispatcher'>;
}
declare module 'barba.js/src/index.js' {
  declare module.exports: $Exports<'barba.js/src/index'>;
}
declare module 'barba.js/src/Pjax/Dom.js' {
  declare module.exports: $Exports<'barba.js/src/Pjax/Dom'>;
}
declare module 'barba.js/src/Pjax/HistoryManager.js' {
  declare module.exports: $Exports<'barba.js/src/Pjax/HistoryManager'>;
}
declare module 'barba.js/src/Pjax/Pjax.js' {
  declare module.exports: $Exports<'barba.js/src/Pjax/Pjax'>;
}
declare module 'barba.js/src/Pjax/Prefetch.js' {
  declare module.exports: $Exports<'barba.js/src/Pjax/Prefetch'>;
}
declare module 'barba.js/src/Transition/BaseTransition.js' {
  declare module.exports: $Exports<'barba.js/src/Transition/BaseTransition'>;
}
declare module 'barba.js/src/Transition/HideShowTransition.js' {
  declare module.exports: $Exports<'barba.js/src/Transition/HideShowTransition'>;
}
declare module 'barba.js/src/Utils/Utils.js' {
  declare module.exports: $Exports<'barba.js/src/Utils/Utils'>;
}
declare module 'barba.js/src/View/BaseView.js' {
  declare module.exports: $Exports<'barba.js/src/View/BaseView'>;
}
declare module 'barba.js/tests/barba-test.js' {
  declare module.exports: $Exports<'barba.js/tests/barba-test'>;
}
declare module 'barba.js/tests/cache-test.js' {
  declare module.exports: $Exports<'barba.js/tests/cache-test'>;
}
declare module 'barba.js/tests/dispatcher-test.js' {
  declare module.exports: $Exports<'barba.js/tests/dispatcher-test'>;
}
declare module 'barba.js/tests/dom-test.js' {
  declare module.exports: $Exports<'barba.js/tests/dom-test'>;
}
declare module 'barba.js/tests/e2e/test-1/index.js' {
  declare module.exports: $Exports<'barba.js/tests/e2e/test-1/index'>;
}
declare module 'barba.js/tests/e2e/test-1/test.js' {
  declare module.exports: $Exports<'barba.js/tests/e2e/test-1/test'>;
}
declare module 'barba.js/tests/history-test.js' {
  declare module.exports: $Exports<'barba.js/tests/history-test'>;
}
declare module 'barba.js/tests/index.js' {
  declare module.exports: $Exports<'barba.js/tests/index'>;
}
declare module 'barba.js/tests/pjax-test.js' {
  declare module.exports: $Exports<'barba.js/tests/pjax-test'>;
}
declare module 'barba.js/tests/utils-test.js' {
  declare module.exports: $Exports<'barba.js/tests/utils-test'>;
}
declare module 'barba.js/webpack.config.js' {
  declare module.exports: $Exports<'barba.js/webpack.config'>;
}
