// flow-typed signature: 0c5d2308d1903e1c681edefa45a30654
// flow-typed version: <<STUB>>/cloudinary-core_v^2.5.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cloudinary-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cloudinary-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cloudinary-core/cloudinary-core-shrinkwrap' {
  declare module.exports: any;
}

declare module 'cloudinary-core/cloudinary-core-shrinkwrap.min' {
  declare module.exports: any;
}

declare module 'cloudinary-core/cloudinary-core' {
  declare module.exports: any;
}

declare module 'cloudinary-core/cloudinary-core.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cloudinary-core/cloudinary-core-shrinkwrap.js' {
  declare module.exports: $Exports<'cloudinary-core/cloudinary-core-shrinkwrap'>;
}
declare module 'cloudinary-core/cloudinary-core-shrinkwrap.min.js' {
  declare module.exports: $Exports<'cloudinary-core/cloudinary-core-shrinkwrap.min'>;
}
declare module 'cloudinary-core/cloudinary-core.js' {
  declare module.exports: $Exports<'cloudinary-core/cloudinary-core'>;
}
declare module 'cloudinary-core/cloudinary-core.min.js' {
  declare module.exports: $Exports<'cloudinary-core/cloudinary-core.min'>;
}
