// flow-typed signature: 876cf3b998e1fa9fe20fa172d4cd5616
// flow-typed version: <<STUB>>/fetch-intercept_v^2.3.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-intercept'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-intercept' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-intercept/karma.conf.babel' {
  declare module.exports: any;
}

declare module 'fetch-intercept/karma.conf' {
  declare module.exports: any;
}

declare module 'fetch-intercept/lib/browser' {
  declare module.exports: any;
}

declare module 'fetch-intercept/lib/browser.min' {
  declare module.exports: any;
}

declare module 'fetch-intercept/lib/node' {
  declare module.exports: any;
}

declare module 'fetch-intercept/lib/node.min' {
  declare module.exports: any;
}

declare module 'fetch-intercept/test/index' {
  declare module.exports: any;
}

declare module 'fetch-intercept/tests.webpack' {
  declare module.exports: any;
}

declare module 'fetch-intercept/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-intercept/karma.conf.babel.js' {
  declare module.exports: $Exports<'fetch-intercept/karma.conf.babel'>;
}
declare module 'fetch-intercept/karma.conf.js' {
  declare module.exports: $Exports<'fetch-intercept/karma.conf'>;
}
declare module 'fetch-intercept/lib/browser.js' {
  declare module.exports: $Exports<'fetch-intercept/lib/browser'>;
}
declare module 'fetch-intercept/lib/browser.min.js' {
  declare module.exports: $Exports<'fetch-intercept/lib/browser.min'>;
}
declare module 'fetch-intercept/lib/node.js' {
  declare module.exports: $Exports<'fetch-intercept/lib/node'>;
}
declare module 'fetch-intercept/lib/node.min.js' {
  declare module.exports: $Exports<'fetch-intercept/lib/node.min'>;
}
declare module 'fetch-intercept/test/index.js' {
  declare module.exports: $Exports<'fetch-intercept/test/index'>;
}
declare module 'fetch-intercept/tests.webpack.js' {
  declare module.exports: $Exports<'fetch-intercept/tests.webpack'>;
}
declare module 'fetch-intercept/webpack.config.babel.js' {
  declare module.exports: $Exports<'fetch-intercept/webpack.config.babel'>;
}
