// flow-typed signature: 57bc0c826e25e1f60dc978bfe4a99765
// flow-typed version: <<STUB>>/react-app-rewire-stylelint_v^0.1.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-stylelint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-app-rewire-stylelint/index' {
  declare module.exports: $Exports<'react-app-rewire-stylelint'>;
}
declare module 'react-app-rewire-stylelint/index.js' {
  declare module.exports: $Exports<'react-app-rewire-stylelint'>;
}
