// flow-typed signature: c5e135215b6b5789e6d293ec0408b679
// flow-typed version: <<STUB>>/react-app-rewire-eslint_v^0.2.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-app-rewire-eslint/index' {
  declare module.exports: $Exports<'react-app-rewire-eslint'>;
}
declare module 'react-app-rewire-eslint/index.js' {
  declare module.exports: $Exports<'react-app-rewire-eslint'>;
}
