// flow-typed signature: e2a6610896808b4627cd498f2245ceed
// flow-typed version: <<STUB>>/react-css-grid_v^2.0.0-0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-css-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-css-grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-css-grid/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-css-grid/dist/index.js' {
  declare module.exports: $Exports<'react-css-grid/dist/index'>;
}
