// flow-typed signature: 2126ca2afaf4c12af5ff86d968659537
// flow-typed version: <<STUB>>/stylelint-high-performance-animation_v^1.1.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-high-performance-animation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-high-performance-animation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-high-performance-animation/index' {
  declare module.exports: $Exports<'stylelint-high-performance-animation'>;
}
declare module 'stylelint-high-performance-animation/index.js' {
  declare module.exports: $Exports<'stylelint-high-performance-animation'>;
}
