// flow-typed signature: b0ff62ca8c93fd80efdb8b3a132c4eee
// flow-typed version: <<STUB>>/stylelint-config-idiomatic-sass_v^1.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-idiomatic-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-idiomatic-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-idiomatic-sass/helpers' {
  declare module.exports: any;
}

declare module 'stylelint-config-idiomatic-sass/order/box-model' {
  declare module.exports: any;
}

declare module 'stylelint-config-idiomatic-sass/order/content' {
  declare module.exports: any;
}

declare module 'stylelint-config-idiomatic-sass/order/display' {
  declare module.exports: any;
}

declare module 'stylelint-config-idiomatic-sass/order/effects' {
  declare module.exports: any;
}

declare module 'stylelint-config-idiomatic-sass/order/layout' {
  declare module.exports: any;
}

declare module 'stylelint-config-idiomatic-sass/order/positioning' {
  declare module.exports: any;
}

declare module 'stylelint-config-idiomatic-sass/order/style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-idiomatic-sass/helpers.js' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-sass/helpers'>;
}
declare module 'stylelint-config-idiomatic-sass/index' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-sass'>;
}
declare module 'stylelint-config-idiomatic-sass/index.js' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-sass'>;
}
declare module 'stylelint-config-idiomatic-sass/order/box-model.js' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-sass/order/box-model'>;
}
declare module 'stylelint-config-idiomatic-sass/order/content.js' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-sass/order/content'>;
}
declare module 'stylelint-config-idiomatic-sass/order/display.js' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-sass/order/display'>;
}
declare module 'stylelint-config-idiomatic-sass/order/effects.js' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-sass/order/effects'>;
}
declare module 'stylelint-config-idiomatic-sass/order/layout.js' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-sass/order/layout'>;
}
declare module 'stylelint-config-idiomatic-sass/order/positioning.js' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-sass/order/positioning'>;
}
declare module 'stylelint-config-idiomatic-sass/order/style.js' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-sass/order/style'>;
}
