// flow-typed signature: e2b96fd2399835f6b47862fd0e5a2e8c
// flow-typed version: <<STUB>>/stylelint-declaration-use-variable_v^1.7.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-declaration-use-variable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-declaration-use-variable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-declaration-use-variable/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-declaration-use-variable/index' {
  declare module.exports: $Exports<'stylelint-declaration-use-variable'>;
}
declare module 'stylelint-declaration-use-variable/index.js' {
  declare module.exports: $Exports<'stylelint-declaration-use-variable'>;
}
declare module 'stylelint-declaration-use-variable/test/index.js' {
  declare module.exports: $Exports<'stylelint-declaration-use-variable/test/index'>;
}
