// flow-typed signature: 5deeb92ab00c75b66a3c3291a7f9d565
// flow-typed version: <<STUB>>/stylelint-images_v^2.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-images/build/index' {
  declare module.exports: any;
}

declare module 'stylelint-images/build/rules/broken/index' {
  declare module.exports: any;
}

declare module 'stylelint-images/build/rules/index' {
  declare module.exports: any;
}

declare module 'stylelint-images/build/rules/prefer-data-uri/index' {
  declare module.exports: any;
}

declare module 'stylelint-images/build/utils/generate-list-images-urls-nodes' {
  declare module.exports: any;
}

declare module 'stylelint-images/build/utils/get-image' {
  declare module.exports: any;
}

declare module 'stylelint-images/build/utils/index' {
  declare module.exports: any;
}

declare module 'stylelint-images/build/utils/namespace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-images/build/index.js' {
  declare module.exports: $Exports<'stylelint-images/build/index'>;
}
declare module 'stylelint-images/build/rules/broken/index.js' {
  declare module.exports: $Exports<'stylelint-images/build/rules/broken/index'>;
}
declare module 'stylelint-images/build/rules/index.js' {
  declare module.exports: $Exports<'stylelint-images/build/rules/index'>;
}
declare module 'stylelint-images/build/rules/prefer-data-uri/index.js' {
  declare module.exports: $Exports<'stylelint-images/build/rules/prefer-data-uri/index'>;
}
declare module 'stylelint-images/build/utils/generate-list-images-urls-nodes.js' {
  declare module.exports: $Exports<'stylelint-images/build/utils/generate-list-images-urls-nodes'>;
}
declare module 'stylelint-images/build/utils/get-image.js' {
  declare module.exports: $Exports<'stylelint-images/build/utils/get-image'>;
}
declare module 'stylelint-images/build/utils/index.js' {
  declare module.exports: $Exports<'stylelint-images/build/utils/index'>;
}
declare module 'stylelint-images/build/utils/namespace.js' {
  declare module.exports: $Exports<'stylelint-images/build/utils/namespace'>;
}
