// flow-typed signature: 7034f5aa5eee920b48c73673259fa275
// flow-typed version: <<STUB>>/stylelint-number-z-index-constraint_v^2.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-number-z-index-constraint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-number-z-index-constraint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-number-z-index-constraint/index.cjs' {
  declare module.exports: any;
}

declare module 'stylelint-number-z-index-constraint/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-number-z-index-constraint/index.cjs.js' {
  declare module.exports: $Exports<'stylelint-number-z-index-constraint/index.cjs'>;
}
declare module 'stylelint-number-z-index-constraint/index.esm.js' {
  declare module.exports: $Exports<'stylelint-number-z-index-constraint/index.esm'>;
}
