/**
* Authentication Types
*/

export const USER_SIGNED_IN = 'USER_SIGNED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_SIGNED_UP = 'USER_SIGNED_UP';
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_EMAIL = 'USER_UPDATE_EMAIL';
export const USER_UPDATE_COMPANY_NAME = 'USER_UPDATE_COMPANY_NAME';
export const USER_UPDATE_NAME = 'USER_UPDATE_NAME';
export const USER_TOGGLE_AGENCY = 'USER_TOGGLE_AGENCY';
export const USER_SET_PASSWORD = 'USER_SET_PASSWORD';
