export const TRELLO_BOARD_FETCHED = 'TRELLO_BOARD_FETCHED';
export const TRELLO_LIST_FETCHED = 'TRELLO_LIST_FETCHED';
export const TRELLO_CARD_CREATED = 'TRELLO_CARD_CREATED';
export const TRELLO_CARD_UPDATED = 'TRELLO_CARD_UPDATED';
